format_version: 3
pipelines:
  frontend-dev:
    group: build
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/whelanworkmaster/mic-input-test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build-and-deploy:
        environment_variables:
              AWS_REGION: us-east-1
              DOCKER_IMAGE_REPO: mic-input-test
              DOCKER_ECR_REPO: 539142489469.dkr.ecr.us-east-1.amazonaws.com
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          build-and-push-docker-image:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ./pipeline/scripts/docker-build.sh
                command: sh
                run_if: passed
          pull-and-start-docker-image:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ./pipeline/scripts/docker-start.sh
                command: bash
                run_if: passed
